dto = ['{ ' 10 ... 
       '"calculationId": "LUNGV20", ' 10 ...
       '"configuration": { ' 10 ...
       ' "modulesConfiguration": [ ' 10 ...
       '   { ' 10 ...
       '     "computations": [ ' 10 ...
       '       { ' 10 ...
       '         "configuration": "string", ' 10 ...
       '         "identifier": "string", ' 10 ...
       '         "volumeOfInterestName": "string" ' 10 ...
       '       } ' 10 ...
       '     ], ' 10 ...
       '     "moduleName": "string" ' 10 ...
       '   } ' 10 ...
       ' ], ' 10 ...
       ' "volumesOfInterest": [ ' 10 ...
       '   { ' 10 ...
       '     "name": "string", ' 10 ...
       '     "operators": [ ' 10 ...
       '       "string" ' 10 ...
       '     ], ' 10 ...
       '     "rtogs": [ ' 10 ...
       '       "string" ' 10 ...
       '     ] ' 10 ...
       '   } ' 10 ...
       ' ] ' 10 ...
       '}, ' 10 ...
       '"dicomPackage": { ' 10 ...
       ' "images": {}, ' 10 ...
       ' "patientId": "string", ' 10 ...
       ' "planlabel": "string", ' 10 ...
       ' "roiNames": [ ' 10 ...
       '   "string" ' 10 ...
       ' ] ' 10 ...
       '}, ' 10 ...
       '"id": 0, ' 10 ...
       '"mappingRtogRoi": {} ' 10 ...
       '}'];