function [ doseVoi ] = createImageDataForVoi( voi, refDose, forceFullGrid )
    if nargin == 2
        forceFullGrid = false;
    end
    
    if ~forceFullGrid
        doseImage = refDose.pixelData(voi.xCompressed, voi.yCompressed, voi.zCompressed);
        doseImage = voi.pixelData .* doseImage;
        doseImage(doseImage == 0) = NaN;

        doseVoi = Image(voi.pixelSpacingX, ...
                        voi.pixelSpacingY, ...
                        voi.pixelSpacingZ, ...
                        voi.realX(voi.xCompressed), ...
                        voi.realY(voi.yCompressed), ...
                        voi.realZ(voi.zCompressed), ...
                        doseImage);
    else
        doseImage = voi.uncompressedpixelData .* refDose.pixelData;
        doseImage(doseImage == 0) = NaN;

        doseVoi = Image(voi.pixelSpacingX, ...
                        voi.pixelSpacingY, ...
                        voi.pixelSpacingZ, ...
                        voi.realX, ...
                        voi.realY, ...
                        voi.realZ, ...
                        doseImage);
    end

end

