function data = createListDicomObjectsForPlan(patientObj, planLabel)
    
    data = createHeader();
    
    patientId = patientObj.id;
    [plan, dose, struct, ct] = patientObj.createPlanPackage(planLabel);
    
    data = addEntry(data, patientId, planLabel,...
                    'RTPLAN', ...
                    plan.studyInstanceUid, ...
                    plan.seriesInstanceUid, ...
                    plan.sopInstanceUid, ...
                    plan.dicomHeader.Filename);
                
    for i = 1:length(dose)
       data = addEntry(data, patientId, planLabel,...
                    'RTDOSE', ...
                    dose(i).studyInstanceUid, ...
                    dose(i).seriesInstanceUid, ...
                    dose(i).sopInstanceUid, ...
                    dose(i).dicomHeader.Filename); 
    end
    
    data = addEntry(data, patientId, planLabel,...
                    'RTSTRUCT', ...
                    struct.studyInstanceUid, ...
                    struct.seriesInstanceUid, ...
                    struct.sopInstanceUid, ...
                    struct.dicomHeader.Filename);
                
    for i = 1:ct.numberOfSlices       
        data = addEntry(data, patientId, planLabel,...
                    'CT', ...
                    ct.ctSlices(i).studyInstanceUid, ...
                    ct.ctSlices(i).seriesInstanceUid, ...
                    ct.ctSlices(i).sopInstanceUid, ...
                    ct.ctSlices(i).dicomHeader.Filename);
    end
end

function data = createHeader()
    data{1,1} = 'patientId';
    data{1,2} = 'planLabel';
    data{1,3} = 'modality';
    data{1,4} = 'studyInstanceUid';
    data{1,5} = 'seriesInstanceUid';
    data{1,6} = 'sopInstanceUid';
    data{1,7} = 'fullfile location';
end

function data = addEntry(data, patientId, planLabel, modality, studyUid, seriesUid, sopUid, file)
    i = size(data,1) + 1;
    data{i,1} = patientId;
    data{i,2} = planLabel;
    data{i,3} = modality;
    data{i,4} = studyUid;
    data{i,5} = seriesUid;
    data{i,6} = sopUid;
    data{i,7} = file;
end

