function [ voiImage ] = createImageDataForVoi( voi, refImage, forceFullGrid )
    if nargin == 2
        forceFullGrid = false;
    end
    
    if ~forceFullGrid
        image = refImage.pixelData(voi.xCompressed, voi.yCompressed, voi.zCompressed);
        image = voi.pixelData .* image;
        image(image == 0) = NaN;

        voiImage = Image(voi.pixelSpacingX, ...
                        voi.pixelSpacingY, ...
                        voi.pixelSpacingZ, ...
                        voi.realX(voi.xCompressed), ...
                        voi.realY(voi.yCompressed), ...
                        voi.realZ(voi.zCompressed), ...
                        image);
    else
        image = voi.uncompressedpixelData .* refImage.pixelData;
        image(image == 0) = NaN;

        voiImage = Image(voi.pixelSpacingX, ...
                        voi.pixelSpacingY, ...
                        voi.pixelSpacingZ, ...
                        voi.realX, ...
                        voi.realY, ...
                        voi.realZ, ...
                        image);
    end
end